name: Update Stock Data

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday at midnight
  push:
    branches:
      - main

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements1.txt

    - name: Run stock data script
      run: python generate_stock_data.py --ticker "QCOM"

    - name: Check for CSV changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        if git diff --exit-code --quiet -- '*.csv'; then
          echo "No CSV changes to commit"
        else
          git add '*.csv'
          git commit -m "Update stock data CSV files"
          git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}